# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StompClientLibExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StompClientLibExample
  pod 'StompClientLib', :path => '../'



  target 'StompClientLibExampleTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'SocketRocket'
  end

  target 'StompClientLibExampleUITests' do
    # Pods for testing
  end

end
